version: 2
jobs:
  build:
    working_directory: ~/shadow
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      - TERM: "dumb"
      - GRADLE_OPTS: "-Xmx1024m"
    steps:
      - checkout
      - run: ./gradlew downloadDependencies
      - run: ./gradlew build --scan
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  deploy-snapshot:
    working_directory: ~/shadow
      docker:
        - image: circleci/openjdk:8-jdk
      environment:
        - TERM: "dumb"
        - GRADLE_OPTS: "-Xmx1024m"
      steps:
        - run: ./gradlew artifactoryPublish

workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy-snapshot:
          requires:
            - build
          filters:
            branches:
              only: master
